apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: vwsvy9gbj-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: vwsvy9gbj-python 
  name: vwsvy9gbj-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: vwsvy9gbj-python 
